/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Zelad (https://sketchfab.com/zelad3d)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/campfire-fcb278e6a64c4a34ba84b2b1fce8c3c0
title: Campfire
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Campfire(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/campfire/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="fire_part_00_3" position={[-0.11, -0.26, -0.1]} rotation={[Math.PI / 2, 0, 0]} scale={0.04}>
                <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.Campfire_fire_MAT}/>
              </group>
              <group name="fire_part_01_4" position={[0.03, 0.36, 0.02]} rotation={[Math.PI / 2, 0, 0.27]} scale={0}>
                <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.Campfire_fire_MAT} />
              </group>
              <group name="fire_part_02_5" position={[-0.08, -0.62, 0.03]} rotation={[Math.PI / 2, 0, 0]} scale={0.04}>
                <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.Campfire_fire_MAT} />
              </group>
              <group name="fire_part_03_6" position={[-0.02, 1.58, 0.01]} rotation={[Math.PI / 2, 0, 0]} scale={0}>
                <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.Campfire_fire_MAT} />
              </group>
              <group name="fire_part_04_7" position={[0.24, -0.59, -0.3]} rotation={[Math.PI / 2, 0, 0]} scale={0}>
                <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.Campfire_fire_MAT} />
              </group>
              <group name="fire_part_05_8" rotation={[Math.PI / 2, 0, 0]} scale={0.04}>
                <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.Campfire_fire_MAT} />
              </group>
              <group name="fire_part_06_9" position={[0.1, -0.41, 0.03]} rotation={[Math.PI / 2, 0, 0]} scale={0.04}>
                <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.Campfire_fire_MAT} />
              </group>
              <group name="fire_part_07_10" position={[-0.42, -1.98, 0.14]} rotation={[1.98, 0, 0]} scale={0.04}>
                <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.Campfire_fire_MAT} />
              </group>
              <group name="fire_part_08_11" position={[0.17, -0.7, -0.22]} rotation={[Math.PI / 2, 0.5, 0]} scale={0.08}>
                <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.Campfire_fire_MAT} />
              </group>
              <group name="fire_part_09_12" position={[0.5, -1.26, 0.21]} rotation={[0.92, 0, 0]} scale={0.04}>
                <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.Campfire_fire_MAT} />
              </group>
              <group name="fire_part_010_13" position={[-0.1, -0.56, 0.16]} rotation={[Math.PI / 2, -0.51, 0]} scale={0.08}>
                <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials.Campfire_fire_MAT} />
              </group>
              <group name="fire_part_011_14" position={[0.68, 0.23, 0.47]} rotation={[Math.PI / 2, 0, 0]} scale={0.04}>
                <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.Campfire_fire_MAT} />
              </group>
              <group name="fire_part_012_15" position={[0.59, 0.89, -0.73]} rotation={[1.59, 0.14, -0.04]} scale={0.03}>
                <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials.Campfire_fire_MAT} />
              </group>
              <group name="fire_part_013_16" position={[-0.8, 0.12, 0.32]} rotation={[1.8, 0.14, -0.08]} scale={0.04}>
                <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.Campfire_fire_MAT} />
              </group>
              <group name="fire_part_014_17" position={[0.09, -1.51, -0.21]} rotation={[Math.PI / 2, 0, 0]} scale={0.08}>
                <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.Campfire_fire_MAT} />
              </group>
              <group name="fire_part_015_18" position={[0.18, -0.55, -0.26]} rotation={[Math.PI / 2, 0, 0]} scale={0.08}>
                <mesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials.Campfire_fire_MAT} />
              </group>
              <group name="fire_part_016_19" position={[0, -1.02, -0.02]} rotation={[Math.PI / 2, 0, 0]} scale={0.12}>
                <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials.Campfire_fire_MAT} />
              </group>
              <group name="fire_part_017_20" position={[-0.12, -1.16, 0.54]} rotation={[Math.PI / 2, 0, 0]} scale={0.12}>
                <mesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials.Campfire_fire_MAT} />
              </group>
              <group name="fire_part_018_21" position={[-0.21, -1.09, -0.61]} rotation={[Math.PI / 2, 0, 0]} scale={[0, 0.04, 0.04]}>
                <mesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials.Campfire_fire_MAT} />
              </group>
              <group name="fire_part_019_22" position={[0.27, -0.93, 0.04]} rotation={[Math.PI / 2, 0, 0]} scale={0.12}>
                <mesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials.Campfire_fire_MAT} />
              </group>
              <group name="fire_part_020_23" position={[0, -0.99, -0.19]} rotation={[Math.PI / 2, 0, 0]} scale={0.08}>
                <mesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials.Campfire_fire_MAT} />
              </group>
              <group name="fire_part_021_24" position={[-0.25, -0.36, 0.03]} rotation={[Math.PI / 2, 0, 0]} scale={0.12}>
                <mesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials.Campfire_fire_MAT} />
              </group>
              <group name="fire_part_022_25" position={[0.17, -0.28, -0.36]} rotation={[Math.PI / 2, 0, 0]} scale={0.08}>
                <mesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials.Campfire_fire_MAT} />
              </group>
              <group name="fire_part_023_26" position={[0.49, -0.28, 0.15]} rotation={[Math.PI / 2, 0, 0]} scale={0.08}>
                <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials.Campfire_fire_MAT} />
              </group>
              <group name="fire_part_024_27" position={[0.49, -0.45, 0.15]} rotation={[Math.PI / 2, 0, 0]} scale={0.04}>
                <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials.Campfire_fire_MAT} />
              </group>
              <group name="fire_part_025_28" position={[-0.12, 0.05, 0.54]} rotation={[Math.PI / 2, 0, 0]} scale={0.04}>
                <mesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials.Campfire_fire_MAT} />
              </group>
              <group name="fire_part_026_29" position={[0.09, -1.08, -0.21]} rotation={[Math.PI / 2, 0, 0]} scale={0.04}>
                <mesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials.Campfire_fire_MAT} />
              </group>
              <group name="fire_part_027_30" position={[0.09, -0.66, -0.21]} rotation={[Math.PI / 2, 0, 0]} scale={0.04}>
                <mesh name="Object_60" geometry={nodes.Object_60.geometry} material={materials.Campfire_fire_MAT} />
              </group>
              <group name="fire_part_028_31" position={[-0.01, -1.7, -0.08]} rotation={[Math.PI / 2, 0, 0]} scale={0.04}>
                <mesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials.Campfire_fire_MAT} />
              </group>
              <group name="Campfire_2" rotation={[Math.PI / 2, 0, 0]} scale={0.04}>
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.Campfire_MAT} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/campfire/scene.gltf')
